### ISSUE TITLE
using tqdm topic evaluation 

### ISSUE THREAD

**Issue by AllenAnsari** [WZBSocialScienceCenter/tmtoolkit#16]
How I can use tdqm in topic evaluation to see what is going on and what percentage of evaluation done/remaining

**Comment by internaut** [comment]
I have no idea what you mean by "tdqm". If you mean some kind of progress bar, there's no such thing currently implemented.

If you want to see what's going on while the processing is running, you may want to enable logging output: https://tmtoolkit.readthedocs.io/en/latest/preprocessing.html#Optional:-enabling-logging-output
