### ISSUE TITLE
Corpus.from_tabular add filenames as prefix to doc_labels.

### ISSUE THREAD

**Issue by fatihbozdag** [WZBSocialScienceCenter/tmtoolkit#21]
Greetings,
Corpus.from_tabular function adds source file name as prefix to each doc_label identifier. Is there a way to prevent this? 
 
`corpus = Corpus.from_tabular('/metadata_with_text.csv', id_column = 'docid_field', text_column = 'text_field)`
`x = corpus.doc_labels`
`x[0:10]`
```
['metadata_with_text-BGSU1001',
 'metadata_with_text-BGSU1002',
 'metadata_with_text-BGSU1003',
 'metadata_with_text-BGSU1004',
 'metadata_with_text-BGSU1005',
 'metadata_with_text-BGSU1006',
 'metadata_with_text-BGSU1007',
 'metadata_with_text-BGSU1008',
 'metadata_with_text-BGSU1009',
 'metadata_with_text-BGSU1010']
```
`prefix = None` as passed to `pd.read_csv` did not work.

**Comment by internaut** [comment]
Yes, you can change the default document label format by passing the parameter `doc_label_fmt='{id}'`. See https://tmtoolkit.readthedocs.io/en/latest/api.html#tmtoolkit.corpus.Corpus.add_tabular

**Comment by fatihbozdag** [comment]
Great! I do not know how I missed that parameter. 

Meanwhile another question; is it possible to implement custom metadata to docs within corpus object? Like the speaker, speaker-gender, native-language, etc. which are provided in the CSV file along with the text? Honestly, I did not really get how to use `preproc.add_metadata_per_doc` function.
