### ISSUE TITLE
Support spacy 3.x

### ISSUE THREAD

**Issue by Siedlerchr** [WZBSocialScienceCenter/tmtoolkit#22]
I am using spacy 3.x and when I wanted to test with tmtoolkit it was installing version 2.x of spacy.

**Comment by internaut** [comment]
Hi, I'm currently working on a new version of tmtoolkit which will support SpaCy 3.x. However, it's still in development and will sure take some weeks to complete.

**Comment by Siedlerchr** [comment]
Thanks for the quick reply! Looking forward to it!

**Comment by internaut** [comment]
New version v0.11.0 has been released with support for SpaCy 3.2. See https://tmtoolkit.readthedocs.io/en/latest/version_history.html for details.
