### ISSUE TITLE
gensim documentation

### ISSUE THREAD

**Issue by doylek1** [WZBSocialScienceCenter/tmtoolkit#25]
Hi. I've been playing around with this toolkit and really enjoying myself. I've had a bit of trouble following the documentation for gensim. Specifically, I keep getting odd results when trying to generate word clouds. I think I'm using the wrong equivalent of the lda .topic_word_ and .doc_topic_ as I keep getting throw unusual vocab terms instead of the top ones. If you could point me in the direct of the proper gensim equivalents, that would be great? Cheers.

**Comment by internaut** [comment]
Yes, gensim has a different approach in regard to accessing the topic-word and document-topic distributions. If `model` is a gensim `LdaModel`, you can access the topic-word distrib. via `model.state.get_lambda()` and the doc.-topic distrib. via the following code.

```python
doc_topic_list = []
for doc_topic in model.get_document_topics(corpus):
    d = dict(doc_topic)
    # Gensim will not output near-zero prob. topics, hence the "d.get()":
    t = tuple(d.get(ind, 0.) for ind in range(model.num_topics))
    doc_topic_list.append(t)

doc_topic_distrib = np.array(doc_topic_list)
```

Should probably write a helper function for this one day... Anyway, hope this helps!
