### ISSUE TITLE
Looading corpus from an instance

### ISSUE THREAD

**Issue by browndw** [WZBSocialScienceCenter/tmtoolkit#26]
Thanks so much for these useful set of tools. I've had no problem loading a corpus using the `language = 'en'` argument. However, when I try to set load an instance and pass it to 'Corpus.from_folder'  as follows, it gives and error:

`nlp = spacy.load('model-new')`

`corp = Corpus.from_folder('test_corpus', spacy_instance='nlp')`

And this happens, as well, if I load the 'en_core_web_sm' model. The error is:

---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
Input In [26], in <cell line: 1>()
----> 1 corp = Corpus.from_folder('test_corpus', spacy_instance='nlp')

File ~/anaconda3/envs/ds_spacy/lib/python3.10/site-packages/tmtoolkit/corpus/_corpus.py:645, in Corpus.from_folder(cls, folder, **kwargs)
    636 """
    637 Construct Corpus object by loading files from a folder `folder`. Pass arguments for Corpus initialization and
    638 file loading as keyword arguments via `kwargs`. See :meth:`~tmtoolkit.corpus.Corpus.__init__` for Corpus
   (...)
    642 :return: Corpus instance
    643 """
    644 from ._corpusfuncs import corpus_add_folder
--> 645 return cls._construct_from_func(corpus_add_folder, folder, **kwargs)

File ~/anaconda3/envs/ds_spacy/lib/python3.10/site-packages/tmtoolkit/corpus/_corpus.py:964, in Corpus._construct_from_func(cls, add_fn, *args, **kwargs)
    961 add_fn_args, corpus_args = split_func_args(add_fn, kwargs)
    962 add_fn_args['inplace'] = True
--> 964 corp = cls(**corpus_args)
    965 add_fn(corp, *args, **add_fn_args)
    966 return corp

File ~/anaconda3/envs/ds_spacy/lib/python3.10/site-packages/tmtoolkit/corpus/_corpus.py:248, in Corpus.__init__(self, docs, language, language_model, load_features, add_features, raw_preproc, spacy_token_attrs, spacy_instance, spacy_opts, punctuation, max_workers, workers_timeout)
    245 # store pipeline configuration for possible re-creation of the instance during copy/deserialize
    246 nlp_conf_allowed_keys = {'lang', 'pipeline', 'disabled', 'before_creation', 'after_creation',
    247                          'after_pipeline_creation', 'batch_size'}
--> 248 nlp_conf = {k: v for k, v in self.nlp.config['nlp'].items() if k in nlp_conf_allowed_keys}
    249 self._spacy_opts = spacy_kwargs
    250 self._spacy_opts.update({'config': {'nlp': nlp_conf}})

AttributeError: 'str' object has no attribute 'config'

I may well just have done this incorrectly, as I couldn't find examples of how to set this up. Thanks in advance.

**Comment by internaut** [comment]
When you write

    corp = Corpus.from_folder('test_corpus', spacy_instance='nlp')

you're passing a string "nlp" to the function. However, you want to pass the variable `nlp`. So you need to write the following:

    corp = Corpus.from_folder('test_corpus', spacy_instance=nlp)

**Comment by browndw** [comment]
I figured it was something this easy. Works. Thank you!
