### ISSUE TITLE
Installation of different versions

### ISSUE THREAD

**Issue by bohnste** [WZBSocialScienceCenter/tmtoolkit#30]
I tried to update on the latest version (0.11.2). However, it seems to be that there is no automatic update option as with -U tmtoolkit it was not possible. 

tmtoolkit==0.10.0

(tmt_2023) (base) C:\Work_TMT_2023>pip install -U tmtoolkit 
Requirement already satisfied: tmtoolkit in c:\work_tmt_2023\tmt_2023\lib\site-packages (0.10.0)

How can I install certain versions , I would like to test the latest version?

Thanks a lot and best wishes,

Stephan

**Comment by internaut** [comment]
What's the Python version you're using when trying to install the package? Make sure it's Python 3.8 or newer (up to 3.10). For older versions, the package is not available.

**Comment by bohnste** [comment]
Thanks, I used python 3.9 but it was not working with -U tmtoolkit. It just checked for site-package (0.10.10) see below. Is there another possibility to install a specific version e.g. 0.11.0 or 0.11.2?


(tmt_2023) (py39) C:\Work_TMT_2023>pip install -U pip
Requirement already satisfied: pip in c:\work_tmt_2023\tmt_2023\lib\site-packages (23.0)

(tmt_2023) (py39) C:\Work_TMT_2023>pip install -U "tmtoolkit[recommended,lda]"
Requirement already satisfied: tmtoolkit[lda,recommended] in c:\work_tmt_2023\tmt_2023\lib\**site-packages (0.10.0)**
...

**Comment by bohnste** [comment]
Ok, I will try it again.

**Comment by bohnste** [comment]
Thanks a lot!
