### ISSUE TITLE
MemoryError with Free Memory while Generating DTM

### ISSUE THREAD

**Issue by pdiegmann** [WZBSocialScienceCenter/tmtoolkit#4]
Hi everybody,

I'm getting a MemoryError while generating the dtm based on my data while still having roughly 8GB of free memory. I'm using Python 3.6.5 64 bit on Ubuntu 18.04 (64 bit of course).
While generating the DTM, memory usage rises roughly 2GB and then exits with the following log:
```
INFO:tmtoolkit:generating DTM
Traceback (most recent call last):
  File "lda_evaluation.py", line 61, in <module>
    doc_labels, vocab, dtm = preproc.get_dtm()
  File "/mnt/hgfs/Downloads/tmtoolkit-master/tmtoolkit/preprocess.py", line 554, in get_dtm
    vocab, doc_labels, docs_terms, dtm_alloc_size = get_vocab_and_terms(tok)
  File "/mnt/hgfs/Downloads/tmtoolkit-master/tmtoolkit/dtm.py", line 40, in get_vocab_and_terms
    return np.array(list(vocab)), np.array(list(docs_terms.keys())), docs_terms, sum_uniques_per_doc
MemoryError
```
To give you an idea of the data / the corpus object, for which I am trying to generate the DTM, uses 90.79MB.

Executing something like
```
import zlib;
print(zlib.crc32(b'a'*(1<<33)))
```
fills the ram, but works fine though.

Any ideas are greatly appreciated.

**Comment by internaut** [comment]
Please investigate `vocab` and `list(docs_terms.keys())` with a debugger and see how many elements they have and how long the strings are that they contain.

**Comment by pdiegmann** [comment]
Alright, I got the following:
299,657 items in vocab 
166,742 keys in doc_terms
length of the strings in vocab: 8,304,279 characters
length of the strings in doc_terms: 1,348,561 characters

**Comment by pdiegmann** [comment]
Update: 
```np.array(list(docs_terms.keys()))```
runs fine, as does
```list(vocab)```
but the conversion into a numpy array runs out of memory.

**Comment by internaut** [comment]
The calls to `np.array` are not very memory efficient, I have to confess. If you don't mind patching your tmtoolkit package, you can try out the following in `dtm.py` and replace the return statement in `get_vocab_and_terms` with this code:

```
    doc_labels = docs_terms.keys()
    return np.fromiter(vocab, dtype='<U%d' % max(map(len, vocab)), count=len(vocab)), \
           np.fromiter(doc_labels, dtype='<U%d' % max(map(len, doc_labels)), count=len(docs_terms)),\
           docs_terms, sum_uniques_per_doc
```

It passes the tests so it should work. However, I'm not sure if it's sufficient for your problem. I will add the changes to a new version of tmtoolkit anyway if it shows to be beneficial.

**Comment by pdiegmann** [comment]
Sadly, it's not sufficient – I still run in MemoryErrors

**Comment by pdiegmann** [comment]
I am currently trying to add the data step by step to the vocab array. This seems quite promising, but is extremely slow. We'll see how it works out.

**Comment by internaut** [comment]
Are you sure that there are not extremely long strings in your vocab? You should check the max. string size in your input tokens.

I *think* that NumPy creates a string buffer that has an alignment with the largest string, i.e.:

```
arr = np.array(['a', 'ab', 'c' * 30])
#  -> array(['a', 'ab', 'cccccccccccccccccccccccccccccc'], dtype='<U30')
arr.dtype.itemsize
# -> 120 bytes (30 * 4 bytes for EACH element)
arr.nbytes
# -> 360 bytes (3 * 120 bytes)
```

Hence the largest string (30 characters) determines the "item size" for the whole array.

Due to the indexing functions of NumPy, I *have* to use it in tmtoolkit, although it is not so memory efficient.

**Comment by pdiegmann** [comment]
Okay, that explains quite a lot.
The longest item is 117,660 characters with an average of 27 characters.
To get all these items into the one array, I'd need about 35GB of memory... 
So I guess, I'll have a look, which one is so excessively long.

Thanks for all the support though!
