### ISSUE TITLE
Vocab size differ for gensim.lda using predefined dictionary

### ISSUE THREAD

**Issue by ramarahmanda** [WZBSocialScienceCenter/tmtoolkit#8]
I'm getting error ```shapes of provided `topic_word_distrib` and `dtm` do not match (vocab sizes differ)``` when trying to evaluate metrics `oherence_mimno_2011`. After debugging I realize that it's happen because I'm using predefined dictionary with length of 8194 and when I try to train data with max dictionary of 8187, the generated dtm is only getting shape of 8188 and the error occured.

**Comment by internaut** [comment]
I can't help you without a minimal, reproducible code example.

**Comment by ramarahmanda** [comment]
@internaut 
```
           some_dict = [..]
           dict_skills = Dictionary([some_dict])
           # len(dict_skills.keys()) = 8194
           train_data = [...] # contains list of bow using dict_skills as dictionary
           # shape (1606, 8187)
           const_params = dict(chunksize=20000,
                            passes=7,
                            alpha='asymmetric',
                            random_state=1)
            varying_params = [dict(num_topics=k)
                              for k in list(range(5, 51, 5))]
            models = tm_gensim.evaluate_topic_models(
                (dict_skills, train_data), varying_params, const_params, metric=(
                    # 'perplexity',
                    # 'cao_juan_2009',
                    'coherence_mimno_2011',
                    # 'coherence_gensim_c_v'
                ), return_models=True)
```
Raise an Exception ```shapes of provided `topic_word_distrib` and `dtm` do not match (vocab sizes differ)```

I already monkey patch this issue by appending latest key from `dict_skills` to `train_data`
```
            _max = 0
            for row in train_data:
                for col in row:
                    if col[0] > _max:
                        _max = col[0]
            d_keys = dict_skills.keys()
            if _max < d_keys[-1]:
                train_data[0].append((d_keys[-1], 0))
```
The problem raise because it convert `train_data` to `dtm` independently (not using specified dictionary).

**Comment by internaut** [comment]
Sorry, I think this is a rather special use case and I don't have the time to implement that at the moment.
